/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Your ENDED activities, newest first, with participant count and average score (PRD RP1). `room` limits them to one room; 404 `not_found` when that room does not exist or belongs to another teacher. For a report's detail, use `GET /activities/{id}/teacher-state`. */
        get: operations["reports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete an ended activity's report: its questions, participants and answers (PRD RP4). 409 `activity_live` while it is running: end it first. 404 when the activity does not exist or belongs to another teacher. */
        delete: operations["activities_destroy"];
        options?: never;
        head?: never;
        /** @description Change display settings: `hide_results` (PRD L4). Works on ended activities too. The teacher's socket gets `activity_updated`; students get nothing (they never see results). Setting the current value is a no-op, so retries are safe. 404 when the activity does not exist or belongs to another teacher. */
        patch: operations["activities_partial_update"];
        trace?: never;
    };
    "/api/activities/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description End the activity and lock all its responses. Ending an already ended activity is a no-op (200). 404 when the activity does not exist or belongs to another teacher. */
        post: operations["activities_end"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}/navigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Teacher-paced: show question `index` to everyone (Next / Previous). Answers to the question being left are locked. Navigating to the current question is a no-op, so retries are safe. 400 `invalid_index` when out of range; 409 `activity_ended` or `not_teacher_paced`. 404 when the activity does not exist or belongs to another teacher. */
        post: operations["activities_navigate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a participant (PRD L5): their token stops working, they leave the live view and the report, and their screen gets `participant_removed`. They can join again unless the room is locked. Works on ended activities too. Removing someone already removed (or who left) is a no-op (204), so retries are safe. 404 `participant_not_found` when they aren't in this activity. 404 when the activity does not exist or belongs to another teacher. */
        delete: operations["activities_participant_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}/report.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The report as a CSV download, UTF-8 with a byte order mark (PRD RP3): one row per participant with `name, joined_at, finished_at, score, total_possible, percent`, then one column per question (header `Q1: <prompt>`, prompt truncated to 60 characters) holding the answer text. Works for LIVE activities too (a snapshot). Errors are JSON. 404 when the activity does not exist or belongs to another teacher. */
        get: operations["reports_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}/teacher-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Full teacher view: activity, questions with answers, participants, responses and per-question summaries. 404 when the activity does not exist or belongs to another teacher. */
        get: operations["activities_teacher_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start Vote (PRD QQ4): end this LIVE short answer quick question and start a quick MC question with the same prompt whose options are its distinct answers (trimmed, case-insensitive; spelled as first submitted, in submission order). Returns the new activity. 409 `not_short_answer` unless this is an SA quick question; `activity_ended` when it is no longer LIVE (e.g. a retry after the vote started); `not_enough_answers` with fewer than 2 distinct answers. 404 when the activity does not exist or belongs to another teacher. */
        post: operations["activities_vote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 403 `email_not_verified` when the password is right but the email is not verified yet. */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Token endpoints need no JWT, so a stale access token header never gets in the way. */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Always 200, whether or not an account exists for the email. */
        post: operations["auth_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `uid` and `token` come from `{FRONTEND_URL}/reset-password?uid=...&token=...` (valid 1 hour, single use). 400 `invalid_or_expired_token`, or `validation_error` with `fields.new_password`. Logs the teacher out everywhere and marks the email verified. */
        post: operations["auth_password_reset_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Token endpoints need no JWT, so a stale access token header never gets in the way. */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates the account and emails a verification link. Returns no tokens: login answers 403 `email_not_verified` until the link is used. */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Always 200, whether or not the email belongs to an unverified account. */
        post: operations["auth_resend_verification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `token` comes from the emailed link `{FRONTEND_URL}/verify-email?token=...`. Idempotent. 400 `invalid_or_expired_token` for a bad, expired (3 days) or stale link. */
        post: operations["auth_verify_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Student-paced: finish the activity. Every answer given is locked (with feedback on, each now carries its `feedback`) and no more answers are accepted. Finishing again is a no-op (200), so retries are safe. 409 `activity_ended` or `not_student_paced`. 401 `invalid_participant_token` when the token is missing, unknown, or the participant left or was removed. */
        post: operations["participant_finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Leave the activity: the token stops working; saved answers are kept. 401 `invalid_participant_token` when the token is missing, unknown, or the participant left or was removed. */
        post: operations["participant_leave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant/responses/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Save your answer (upsert; safe to retry). 400 `invalid_answer`; 404 `question_not_found` if the question isn't in your activity; 409 `activity_ended`, `not_current_question`, `already_finished` or `response_locked`. 401 `invalid_participant_token` when the token is missing, unknown, or the participant left or was removed. */
        put: operations["participant_response_submit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Everything the student screen needs. Correct answers appear only in `response.feedback`, and only when feedback is on and that answer is locked. 401 `invalid_participant_token` when the token is missing, unknown, or the participant left or was removed. */
        get: operations["participant_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The teacher's quizzes, most recently edited first. */
        get: operations["quizzes_list"];
        put?: never;
        /** @description Create a quiz with its full list of questions. 400 `validation_error` when any rule of PRD Q1–Q5 is broken; `fields` keys are paths such as `title`, `questions` or `questions.2.choices` (0-based question index). */
        post: operations["quizzes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The quiz with its questions in order. 404 when the quiz does not exist or belongs to another teacher. */
        get: operations["quizzes_retrieve"];
        /** @description Replace the title and the whole questions array in one transaction. Questions missing from the body are deleted. Nothing changes on error. 400 `validation_error` when any rule of PRD Q1–Q5 is broken; `fields` keys are paths such as `title`, `questions` or `questions.2.choices` (0-based question index). 404 when the quiz does not exist or belongs to another teacher. */
        put: operations["quizzes_update"];
        post?: never;
        /** @description Deletes the quiz. Reports of activities run from it are kept. 404 when the quiz does not exist or belongs to another teacher. */
        delete: operations["quizzes_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Copy the quiz and its questions as a new quiz titled "<title> (copy)". 404 when the quiz does not exist or belongs to another teacher. */
        post: operations["quizzes_duplicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The teacher's rooms, newest first. */
        get: operations["rooms_list"];
        put?: never;
        /** @description Without `code`, a unique 6-character code is generated. A custom code that is malformed or taken answers 400 `validation_error` with `fields.code`. */
        post: operations["rooms_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Join the room's LIVE activity. 404 `room_not_found`, 423 `room_locked` (unless `X-Participant-Token` shows you already joined this room and weren't removed), 409 `no_live_activity` (wait for the teacher), 429 `throttled`. The token is only returned here. */
        post: operations["rooms_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{code}/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 404 `room_not_found` for an unknown code. A locked room still answers 200 with `is_locked: true`. */
        get: operations["rooms_public"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 404 when the room does not exist or belongs to another teacher. */
        get: operations["rooms_retrieve"];
        put?: never;
        post?: never;
        /** @description Deletes the room with all its activities and responses. 404 when the room does not exist or belongs to another teacher. */
        delete: operations["rooms_destroy"];
        options?: never;
        head?: never;
        /** @description Rename and/or lock or unlock. Only `name` and `is_locked` can change. 404 when the room does not exist or belongs to another teacher. */
        patch: operations["rooms_partial_update"];
        trace?: never;
    };
    "/api/rooms/{room_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start a Quick Question (`QUICK` + `question`) or a quiz (`QUIZ` + `quiz_id` + `mode`: `TEACHER_PACED` or `STUDENT_PACED`; `shuffle_questions` only with `STUDENT_PACED`). A quiz's questions are copied into the activity, so later edits to the quiz don't affect it. Any LIVE activity in the room is ended first, in the same transaction. 404 `not_found` when the room does not exist or belongs to another teacher; 404 `quiz_not_found` likewise for the quiz (the LIVE activity then keeps running). */
        post: operations["activities_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            readonly id: number;
            readonly room_id: number;
            readonly type: components["schemas"]["ActivityTypeEnum"];
            readonly mode: components["schemas"]["ActivityModeEnum"];
            readonly status: components["schemas"]["ActivityStatusEnum"];
            readonly quiz_title: string;
            /** @description The quiz this was launched from; null for quick questions or once the quiz is deleted. */
            readonly source_quiz_id: number | null;
            readonly current_index: number;
            readonly show_feedback: boolean;
            readonly shuffle_questions: boolean;
            readonly hide_results: boolean;
            readonly version: number;
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            readonly ended_at: string | null;
        };
        /**
         * @description * `TEACHER_PACED` - Teacher Paced
         *     * `STUDENT_PACED` - Student Paced
         * @enum {string}
         */
        ActivityModeEnum: "TEACHER_PACED" | "STUDENT_PACED";
        ActivityStartRequest: {
            type: components["schemas"]["ActivityTypeEnum"];
            /** @description QUICK only, required. */
            question?: components["schemas"]["QuickQuestionRequest"];
            /** @description QUIZ only, required. */
            quiz_id?: number;
            /**
             * @description QUIZ only, required. TEACHER_PACED: everyone sees the question the teacher shows. STUDENT_PACED: each student sees every question, can change answers until they press Finish.
             *
             *     * `TEACHER_PACED` - Teacher Paced
             *     * `STUDENT_PACED` - Student Paced
             */
            mode?: components["schemas"]["ActivityModeEnum"];
            /**
             * @description QUIZ only: answers lock on submit, and students then see correct/incorrect and the explanation for that question.
             * @default false
             */
            show_feedback: boolean;
            /**
             * @description QUIZ, STUDENT_PACED only: each student gets the questions in their own random order.
             * @default false
             */
            shuffle_questions: boolean;
        };
        /**
         * @description * `LIVE` - Live
         *     * `ENDED` - Ended
         * @enum {string}
         */
        ActivityStatusEnum: "LIVE" | "ENDED";
        /**
         * @description * `QUICK` - Quick
         *     * `QUIZ` - Quiz
         * @enum {string}
         */
        ActivityTypeEnum: "QUICK" | "QUIZ";
        AuthResponse: {
            access: string;
            refresh: string;
            user: components["schemas"]["User"];
        };
        Detail: {
            detail: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Shape of every error response (see flashform/exceptions.py). Use in @extend_schema. */
        Error: {
            detail: string;
            code: string;
            /** @description Per-field validation messages; present only on field validation errors. */
            fields?: {
                [key: string]: string[];
            };
        };
        Feedback: {
            is_correct: boolean | null;
            correct_index: number | null;
            accepted_answers: string[];
            explanation: string;
        };
        Health: {
            status: string;
        };
        JoinRequest: {
            /** @description Display name, 1–40 characters, trimmed. */
            name: string;
        };
        JoinResult: {
            /** Format: uuid */
            participant_id: string;
            /** @description Secret for X-Participant-Token. Returned only here: store it. */
            token: string;
            activity_id: number;
        };
        /** @description The room's LIVE activity in the teacher's room list (PRD R2). */
        LiveActivitySummary: {
            id: number;
            type: components["schemas"]["ActivityTypeEnum"];
            mode: components["schemas"]["ActivityModeEnum"];
            quiz_title: string;
            /** Format: date-time */
            started_at: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        NavigateRequest: {
            /** @description 0-based order of the question to show. */
            index: number;
        };
        ParticipantState: {
            activity: components["schemas"]["StudentActivity"];
            participant: components["schemas"]["StudentParticipant"];
            question_count: number;
            /** @description Visible questions: the current one (teacher-paced), all (student-paced, in this student's own order when shuffled), none once the activity has ended. */
            questions: components["schemas"]["StudentQuestion"][];
        };
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            new_password: string;
        };
        PatchedActivityUpdateRequest: {
            /** @description Hide the answer distribution on the teacher's live view (for projecting). Students never see results either way. */
            hide_results?: boolean;
        };
        PatchedRoomUpdateRequest: {
            name?: string;
            is_locked?: boolean;
        };
        PublicRoom: {
            readonly code: string;
            readonly name: string;
            readonly is_locked: boolean;
            /** @description The LIVE activity's id, or null while students should wait. */
            readonly live_activity_id: number | null;
        };
        QuestionSummary: {
            question_id: number;
            answered_count: number;
            /** @description null when the question has no correct answer. */
            correct_count: number | null;
            /** @description Count per choice (MC/TF); [] for SA. */
            choice_counts: number[];
            /** @description SA only: answers grouped trimmed and case-insensitively, most common first. */
            text_counts: components["schemas"]["TextCount"][];
        };
        /**
         * @description * `MC` - Mc
         *     * `TF` - Tf
         *     * `SA` - Sa
         * @enum {string}
         */
        QuestionTypeEnum: "MC" | "TF" | "SA";
        QuickQuestionRequest: {
            type: components["schemas"]["QuestionTypeEnum"];
            /**
             * @description Optional; teachers often ask out loud. Empty means students see "Answer the question your teacher asked."
             * @default
             */
            prompt: string;
            /** @description MC only: 2–6 option labels. Omit for the default A, B, C, D. */
            choices?: string[];
        };
        Quiz: {
            readonly id: number;
            readonly title: string;
            readonly question_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly questions: components["schemas"]["QuizQuestion"][];
        };
        QuizListItem: {
            readonly id: number;
            readonly title: string;
            readonly question_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        QuizQuestion: {
            readonly order: number;
            readonly type: components["schemas"]["QuestionTypeEnum"];
            readonly prompt: string;
            readonly explanation: string;
            /** @description MC options; always [] for TF and SA. */
            choices: string[];
            readonly correct_index: number | null;
            /** @description SA only; [] otherwise. */
            accepted_answers: string[];
        };
        QuizQuestionWriteRequest: {
            type: components["schemas"]["QuestionTypeEnum"];
            /** @description Required, 1–1000 characters, trimmed. */
            prompt: string;
            /**
             * @description Optional, ≤ 2000 characters. Shown to students with feedback.
             * @default
             */
            explanation: string;
            /** @description MC only: 2–6 non-blank options, each ≤ 300 characters. TF and SA: omit or send []; TF always uses True, False. */
            choices?: string[];
            /** @description MC: index into `choices`. TF: 0 = True, 1 = False. Null (or omitted) for no correct answer. SA: must be null. */
            correct_index?: number | null;
            /** @description SA only: up to 20 non-blank answers, each ≤ 500 characters. Students match case-insensitively after trimming. Empty means no correct answer. MC and TF: omit or send []. */
            accepted_answers?: string[];
        };
        /** @description Body of POST /quizzes and PUT /quizzes/{id}: the whole quiz. */
        QuizWriteRequest: {
            /** @description Required, 1–200 characters, trimmed. */
            title: string;
            /** @description 1–100 questions, in order. */
            questions: components["schemas"]["QuizQuestionWriteRequest"][];
        };
        RefreshRequest: {
            refresh: string;
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterResponse: {
            detail: string;
            user: components["schemas"]["User"];
        };
        Report: {
            id: number;
            room: components["schemas"]["ReportRoom"];
            type: components["schemas"]["ActivityTypeEnum"];
            mode: components["schemas"]["ActivityModeEnum"];
            /** @description "" for quick questions. */
            quiz_title: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string;
            /** @description Excludes participants who left while it was live. */
            participant_count: number;
            question_count: number;
            /** @description Questions with a correct answer: the most a participant can score. */
            total_possible: number;
            /**
             * Format: double
             * @description Mean correct answers per participant (2 decimals); null without participants or when total_possible is 0.
             */
            avg_score: number | null;
            /**
             * Format: double
             * @description avg_score as a percentage of total_possible (1 decimal).
             */
            avg_percent: number | null;
        };
        ReportRoom: {
            id: number;
            name: string;
            code: string;
        };
        ResponseSubmitRequest: {
            /** @description MC/TF: 0-based (TF: 0 True, 1 False). */
            choice_index?: number | null;
            /** @description SA: 1–500 characters. */
            text_answer?: string;
        };
        Room: {
            readonly id: number;
            readonly name: string;
            readonly code: string;
            readonly is_locked: boolean;
            /** @description The LIVE activity, or null when nothing is running. */
            readonly live_activity: components["schemas"]["LiveActivitySummary"] | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        RoomCreateRequest: {
            name: string;
            /** @description Optional custom code: 4–10 characters A–Z 0–9, stored uppercase, unique case-insensitively. Omit it (or send null or "") to get a generated 6-character code. */
            code?: string | null;
        };
        StudentActivity: {
            readonly id: number;
            readonly type: components["schemas"]["ActivityTypeEnum"];
            readonly mode: components["schemas"]["ActivityModeEnum"];
            readonly status: components["schemas"]["ActivityStatusEnum"];
            readonly quiz_title: string;
            readonly current_index: number;
            readonly show_feedback: boolean;
            readonly version: number;
        };
        StudentParticipant: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: date-time */
            readonly finished_at: string | null;
        };
        StudentQuestion: {
            id: number;
            /** @description Position in the quiz (0-based). With shuffled questions this is not the position on the student's screen: number questions by their place in `questions`. */
            order: number;
            type: components["schemas"]["QuestionTypeEnum"];
            prompt: string;
            choices: string[];
            /** @description Your saved answer, or null. */
            response: components["schemas"]["StudentResponse"] | null;
        };
        StudentResponse: {
            question_id: number;
            choice_index: number | null;
            text_answer: string;
            is_locked: boolean;
            /** Format: date-time */
            submitted_at: string;
            /** @description Correctness and explanation; null unless feedback is on and the answer is locked. */
            feedback: components["schemas"]["Feedback"] | null;
        };
        TeacherParticipant: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: date-time */
            joined_at: string;
            /**
             * Format: date-time
             * @description Student-paced: when they pressed Finish; null until then.
             */
            finished_at: string | null;
            /** Format: date-time */
            readonly last_seen_at: string;
            /** @description Questions this participant has answered (progress, e.g. 4 of 10). */
            answered_count: number;
            /** @description Questions in the activity. */
            question_count: number;
            /** @description Correct answers. Out of the state's total_possible (PRD §17). */
            score: number;
        };
        TeacherQuestion: {
            readonly id: number;
            readonly order: number;
            readonly type: components["schemas"]["QuestionTypeEnum"];
            readonly prompt: string;
            readonly explanation: string;
            /** @description MC options; ["True", "False"] for TF; [] for SA. */
            choices: string[];
            readonly correct_index: number | null;
            readonly accepted_answers: unknown;
        };
        TeacherResponse: {
            /** Format: uuid */
            participant_id: string;
            question_id: number;
            readonly choice_index: number | null;
            readonly text_answer: string;
            readonly is_correct: boolean | null;
            readonly is_locked: boolean;
            /** Format: date-time */
            readonly submitted_at: string;
        };
        TeacherState: {
            activity: components["schemas"]["Activity"];
            questions: components["schemas"]["TeacherQuestion"][];
            /** @description Joined participants, excluding removed ones. */
            participants: components["schemas"]["TeacherParticipant"][];
            participant_count: number;
            /** @description Questions with a correct answer: the most a participant can score. */
            total_possible: number;
            responses: components["schemas"]["TeacherResponse"][];
            summaries: components["schemas"]["QuestionSummary"][];
        };
        TextCount: {
            answer: string;
            count: number;
        };
        TokenPair: {
            access: string;
            refresh: string;
        };
        User: {
            readonly id: number;
            readonly name: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            readonly email_verified: boolean;
        };
        VerifyEmailRequest: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reports_list: {
        parameters: {
            query?: {
                /** @description Only this room's reports. Omit for all rooms. */
                room?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedActivityUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherState"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_end: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherState"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_navigate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NavigateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherState"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_participant_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
                /** @description Participant id. */
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reports_csv: {
        parameters: {
            query?: {
                /** @description IANA time zone for joined_at / finished_at, e.g. Europe/London (the browser's). Default UTC. */
                tz?: string;
            };
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_teacher_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherState"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_vote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherState"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_password_reset_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_resend_verification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    participant_finish: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /rooms/{code}/join. */
                "X-Participant-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantState"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    participant_leave: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /rooms/{code}/join. */
                "X-Participant-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    participant_response_submit: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /rooms/{code}/join. */
                "X-Participant-Token": string;
            };
            path: {
                /** @description Question id. */
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResponseSubmitRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    participant_state: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /rooms/{code}/join. */
                "X-Participant-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantState"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    quizzes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizListItem"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    quizzes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    quizzes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    quizzes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    quizzes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    quizzes_duplicate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_join: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional: your token from an earlier (or the current) activity in this room. Lets you re-join while the room is locked. */
                "X-Participant-Token"?: string;
            };
            path: {
                /** @description Room code as typed; case-insensitive, spaces ignored. */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResult"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_public: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room code as typed; case-insensitive, spaces ignored. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicRoom"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rooms_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room id. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRoomUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activities_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room id. */
                room_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityStartRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherState"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
